"""
Map Data Generation Pipeline.
This script bridges the Machine Learning backend and the Frontend visualization.
It loads the previously trained Knowledge Graph Embeddings (PyKEEN) and the 
Random Forest price regressor (Scikit-Learn) to predict property values. 
Simultaneously, it queries the RDF graph for semantically inferred properties 
(like 'WellConnectedFlat') and compiles everything into a rich JSON payload for the UI.
"""

import os
import glob
import gzip
import json
import joblib
import torch
import numpy as np
from rdflib import Graph, Namespace, RDF

# ==============================================================================
# Path Definitions & Setup
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

# Path to the fully inferred Knowledge Graph containing the target prices and rules
KG_PATH = os.path.join(PROJECT_ROOT, "src", "3_logic", "inferred_vienna_kg.ttl")
OUTPUT_JSON = os.path.join(PROJECT_ROOT, "src", "map_data.json")
RESULTS_DIR = os.path.join(SCRIPT_DIR, "results")

EX = Namespace("http://vienna-realestate.org/kg/")

# ==============================================================================
# 1. Locate and Load the Saved Models
# ==============================================================================

# Dynamic directory lookup (Commented out in favor of manual override for reproducible portfolio builds)
valid_dirs = [d for d in glob.glob(os.path.join(RESULTS_DIR, "run_*")) 
              if os.path.exists(os.path.join(d, "price_regressor.pkl"))]

if not valid_dirs:
    raise FileNotFoundError("No valid run with price_regressor.pkl found in results!")

LATEST_RUN_DIR = max(valid_dirs, key=os.path.getctime)

# Manual Override: Hardcode a specific run to ensure consistency for the final app data
# MANUAL_RUN_NAME = "run_20261007_070839_RotatE_dim128"
# LATEST_RUN_DIR = os.path.join(RESULTS_DIR, MANUAL_RUN_NAME)
print(f"Loading saved regressor model from: {os.path.basename(LATEST_RUN_DIR)}")

# Load the trained Scikit-Learn Random Forest Regressor
regressor = joblib.load(os.path.join(LATEST_RUN_DIR, "price_regressor.pkl"))

# Load the base Knowledge Graph into memory
print("Loading Knowledge Graph...")
g = Graph()
g.parse(KG_PATH, format="turtle")

# Load the trained PyTorch PyKEEN Knowledge Graph Embedding model
model = torch.load(os.path.join(LATEST_RUN_DIR, "trained_model.pkl"), weights_only=False)

# Reconstruct the entity mapping from the gzipped TSV generated by PyKEEN.
# We need this to map our real-world Flat URIs to PyTorch's internal integer IDs.
entity_to_id = {}
mapping_path = os.path.join(LATEST_RUN_DIR, "training_triples", "entity_to_id.tsv.gz")
with gzip.open(mapping_path, "rt", encoding="utf-8") as f:
    next(f)  # Skip the header row
    for line in f:
        e_id, e_uri = line.strip().split("\t")
        entity_to_id[e_uri] = int(e_id)


# ==============================================================================
# 2. Process Flats, Predict Prices, and Extract Inferred Semantic Rules
# ==============================================================================
map_export = []

# Iterate through every entity in the graph explicitly typed as a 'Flat'
for flat_uri in g.subjects(RDF.type, EX.Flat):
    flat_str = str(flat_uri)
    
    # Extract baseline physical attributes
    price_lit = g.value(flat_uri, EX.hasPrice)
    lat_lit = g.value(flat_uri, EX.latitude)
    lon_lit = g.value(flat_uri, EX.longitude)

    # Only process flats that have an actual price and exist in our PyKEEN vocabulary
    if price_lit and flat_str in entity_to_id:
        actual_price = float(price_lit)
        e_id = entity_to_id[flat_str]

        # --- ML Prediction Block ---
        # 1. Fetch the topological embedding vector from the PyTorch model
        vector = model.entity_representations[0](torch.tensor([e_id], device=model.device)).detach().cpu().numpy()[0]
        
        # 2. Resolve complex numbers for Scikit-Learn (RotatE specific fix)
        vector_real = np.concatenate([vector.real, vector.imag]) if np.iscomplexobj(vector) else vector

        # 3. Predict the estimated market value using the extracted structural features
        pred_price = float(regressor.predict([vector_real])[0])
        
        # 4. A flat is considered a "Good Deal" if the actual listing price is below our model's prediction
        is_good_deal = bool(actual_price < pred_price)

        # --- Semantic Reasoning Block ---
        # Directly query the Graph to see if our logical rules (from the reasoning pipeline) 
        # classified this specific flat. 'in g' checks for the existence of a specific triple.
        is_well_connected = (flat_uri, RDF.type, EX.WellConnectedFlat) in g
        has_direct_access = (flat_uri, EX.hasDirectStationAccess, None) in g

        # Fetch additional descriptive attributes for the UI tooltip
        size_lit = g.value(flat_uri, EX.hasSize) 
        rooms_lit = g.value(flat_uri, EX.hasRooms)

        # Assemble the final dictionary record for this flat
        map_export.append({
            # Fallback to Vienna city center coordinates (Stephansplatz) if exact coordinates are missing
            "LATITUDE": str(round(float(lat_lit), 6)) if lat_lit else "48.2082",
            "LONGITUDE": str(round(float(lon_lit), 6)) if lon_lit else "16.3738",
            
            # Formatted prices for UI display
            "PRICE": str(round(actual_price, 2)),
            "actual_price": round(actual_price, 2),
            "predicted_price": round(pred_price, 2),
            "is_good_deal": is_good_deal,
            
            # Boolean flags derived from Knowledge Graph logical reasoning
            "is_well_connected": is_well_connected,
            "has_direct_access": has_direct_access,
            
            # Physical property stats
            "estate_size": float(size_lit) if size_lit else None,
            "number_of_rooms": int(rooms_lit) if rooms_lit else None,
            
            # Unique identifier for potential deep-linking
            "uri": flat_str
        })


# ==============================================================================
# 3. Export Data to Frontend
# ==============================================================================
# Save the assembled list of dictionaries as a JSON array, which the mapping UI 
# (e.g., Leaflet/Mapbox) can easily ingest and render as markers.
with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(map_export, f, indent=4, ensure_ascii=False)

print(f"\nSuccessfully generated {len(map_export)} flat records.")
print(f"Output saved to: {OUTPUT_JSON}")